In [1]:
import numpy as np

In [14]:
arr = np.array([2,3,4,6,7,8,9,12,13,16,17,23,25,27,34,37,201])
arr

array([  2,   3,   4,   6,   7,   8,   9,  12,  13,  16,  17,  23,  25,
        27,  34,  37, 201])

In [3]:
Q3 = np.percentile(arr, 75)
Q1 = np.percentile(arr, 25)

In [4]:
IQR = Q3-Q1
IQR

np.float64(18.0)

In [5]:
UF=Q3 + (1.5*IQR)
LF=Q1 - (1.5*IQR)

In [18]:
l = []
for i in arr:
    if (i >= LF) & (i <= UF):
        l.append(i)
arr2 = np.array(l)

In [16]:
print(arr)
print(arr2)

[  2   3   4   6   7   8   9  12  13  16  17  23  25  27  34  37 201]
[ 2  3  4  6  7  8  9 12 13 16 17 23 25 27 34 37]
