# NumPy Array

NumPy arrays are used for numerical calculations.

# import numpy = import numpy as np

# creating an array
np.array()

In [5]:
import numpy as np

In [6]:
even = np.array([2,4,6,8])
even

array([2, 4, 6, 8])

# Python lists
  We can used multiple data types.

# Numpy
  same data type like only list, tuple, numbers, string. NumPy arrays are generally designed to contain one common data type (homogeneous data).
  But if you put different data types in the same NumPy array, NumPy will usually convert them to a common compatible type.

 NumPy arrays are homogeneous, meaning they normally store elements of the same data type. If we provide compatible mixed types, NumPy performs type promotion and converts them to a common dtype. If necessary, NumPy can also use object dtype for arbitrary Python objects, but that loses many of the performance advantages of normal NumPy arrays.

Numpy asks like = "What single data type can hold all three values without losing information?"
Integer → ❌ "30" cannot be an integer automatically
Float   → ❌ "30" is still a string
String  → ✅ can represent 10, 20 and "30"

int + float       → float
int + bool        → integer (typically)
int + string      → string
float + string    → string

In [7]:
numberList = [10,20,4.5]
numberList

[10, 20, 4.5]

In [9]:
numbers = np.array([10,20,4.5])
numbers

array([10. , 20. ,  4.5])

# vectors
 created in single one dimensional space means has one row.[1,2,3,4,5]

# Matrix
It is 2-dimensional means has multiple rows and multiple columns.
List can not support this multiple rows and column it gives it in like one dimensional.

In [10]:
singleD = np.array([10,20,30,40,50])
singleD

array([10, 20, 30, 40, 50])

In [15]:
multiD = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
multiD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
l = [[1,2,3], [4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]