# arange = it is like range in python. Creates numbers with a step. 
 np.arange(1,5,2) 

# linspace = Creates evenly spaced numbers.
 np.linspace(1,5,3) = so it gives 3 numbers with evenly space between 1-5

# zeros = Creates array filled with 0
 np.zeros(5)
 

# ones = Creates array filled with 1
 np.ones(5)
 matrix form = np.ones((4, 6)) 4 rows, 6 columns

# np.arrays = create an array

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,20,5)
arr

array([ 1,  6, 11, 16])

In [3]:
arr = np.linspace(1,10,2)
arr

array([ 1., 10.])

In [4]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])