# In numpy library random is automatically installed when numpy library installed.

# np.random.rand = gives random numbers betn 0-1 called as normalization in statistics.

# np.random.randn = gives random numbers betn -3 to 3 called as standardlization in statistics.

# np.random.randint = gives integer number whatever limit you set.
  np.random.randint(6) = gives 0 to 6 any one random number.

# np.random.randint(start, end, how many numbers want)
 np.random.randint(10,20,10) = gives between 10 to 20 , 10 numbers

In [1]:
import numpy as np

In [4]:
arr = np.random.rand(5)
arr

array([0.63038348, 0.02338458, 0.87124045, 0.46786488, 0.15398971])

In [5]:
arr = np.random.randn(10)
arr

array([ 1.0781606 , -1.60983773, -0.47948834, -0.04645303, -0.71872283,
       -1.4186051 ,  0.41905567,  0.93647585,  2.63943063, -0.51461796])

In [6]:
arr = np.random.randint(6)
arr


2

In [8]:
arr = np.random.randint(1, 8, 5)
arr

array([7, 5, 6, 1, 2], dtype=int32)

arr.ndim        # attribute
arr.shape       # attribute
arr.size        # attribute
arr.dtype       # attribute

arr.sum()       # method
arr.mean()      # method
arr.max()       # method
arr.min()       # method
arr.reshape()   # method
arr.flatten()   # method

# Array attributes and methods are not only for 1D or 2D arrays. They work with 1D, 2D, 3D, and higher-dimensional NumPy arrays.

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.size

9

In [11]:
arr.shape

(3, 3)

In [12]:
arr.ndim

2

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.sum()

np.int64(45)

axis = 0 , column wise addition,
axis=1, row wise sum

use np for axis wise sum

In [19]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [20]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.argmin()

np.int64(0)

In [25]:
arr.argmax()

np.int64(8)

In [26]:
arr.mean()

np.float64(5.0)

# reshape = arr.reshape(shape)
 suppose we have 30 numbers in array so need to shape like 6 x 5 or 5 x 6. so that total elements can be equally distrubute.

# resize = to save the reshape result in variable is resize.
 ar = arr.reshape