# access/slice single element = arr[index]
# slice the portion of vector = arr[start:end:step]


In [1]:
import numpy as np

In [4]:
numbers = np.arange(1, 11)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#slice or access single element
single = numbers[8]
single

np.int64(9)

In [6]:
#slice some portion
res = numbers[2:8]
res


array([3, 4, 5, 6, 7, 8])

In [7]:
res = numbers[:6]
res

array([1, 2, 3, 4, 5, 6])

In [8]:
res = numbers[:]
res

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
res = numbers[2:]
res

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# access single matrix = arr[row,column]
# slice column = arr[:column]
# slice row = arr[]

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
res = arr[1,2]
res

np.int64(8)

In [13]:
res = arr[4]
res

array([21, 22, 23, 24, 25])

In [15]:
res = arr[:,3]
res

array([ 4,  9, 14, 19, 24, 29])

In [18]:
res = arr[1:5,1:4]
res

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [19]:
res = arr[2:,3:]
res

array([[14, 15],
       [19, 20],
       [24, 25],
       [29, 30]])

In [26]:
res = numbers[2::3]
res

array([3, 6, 9])

# boolean indexing 

In [27]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
res = arr % 2 == 0
res

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [31]:
bool = arr[res]
bool

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])