In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1, 6)
arr2 = np.arange(6, 11)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [3]:
res= arr1 + arr2
res

array([ 7,  9, 11, 13, 15])

In [4]:
res = arr2 - arr1
res

array([5, 5, 5, 5, 5])

In [5]:
res = arr1 / arr2
res

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
res = arr1 // arr2
res

array([0, 0, 0, 0, 0])

In [7]:
res = arr1 * arr2
res

array([ 6, 14, 24, 36, 50])

In [8]:
res = arr1 ** arr2
res

array([      1,     128,    6561,  262144, 9765625])

In [9]:
m1 = np.arange(1, 5).reshape(2,2)
m2 = np.arange(6, 10).reshape(2,2)

m1, m2

(array([[1, 2],
        [3, 4]]),
 array([[6, 7],
        [8, 9]]))

In [10]:
res = m1 * m2
res

array([[ 6, 14],
       [24, 36]])

In [11]:
res = m1 @ m2
res

array([[22, 25],
       [50, 57]])

In [12]:
res = m1.dot(m2)
res

array([[22, 25],
       [50, 57]])

# broadcasting = in simple way if we want to add single value like 10 to all elements we can add it arr+10, is called broadcasting.

In [13]:
arr3 = np.arange(1,6)
arr3

array([1, 2, 3, 4, 5])

In [14]:
res = arr3 + 20
res

array([21, 22, 23, 24, 25])

In [15]:
arr4 = np.arange(1,7).reshape(3,2)
arr4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [23]:
A.T

array([[1, 3],
       [2, 4]])

In [24]:
arr4.T

array([[1, 3, 5],
       [2, 4, 6]])

# Advance array mnipulation
# stacking = means to to join two arrays. it works with vector not with matrix. has 3 ways vertical, horizontal, column.
# spliting = is used to split array, but needs equal number to split.

In [27]:
c = np.arange(1, 6)
d = np.arange(6, 11)

c,d

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [29]:
v_stack = np.vstack((c,d))
v_stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
h_stack=np.hstack((c,d))
h_stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
c_stack = np.column_stack((c,d))
c_stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [32]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
h_split =np.hsplit(arr4,2)
h_split 

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [37]:
v_split = np.vsplit(arr4,1)
v_split

[array([[1, 2],
        [3, 4],
        [5, 6]])]