In [2]:
import numpy as np

In [53]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [4]:
#Get the shape of the matrix.
res = data.shape
res

(5, 3)

In [5]:
#Find the average age of students.
age = data[:,0].mean()
age

np.float64(18.4)

In [6]:
#Extract Math marks of all students.
maths=data[:,1]
maths

array([85, 92, 76, 65, 90])

In [7]:
#Find the highest Science mark.
science = data[:, 2].max()
science

np.int64(95)

In [8]:
#Get details of the student who scored more than 90 in Math.
more90 = maths > 90
data[more90]


array([[19, 92, 88]])

In [9]:
#Increase Math marks of all students by 5.
res = maths + 5
res

array([90, 97, 81, 70, 95])

In [10]:
#Find how many students are younger than 19.
age=data[:,0]
younger = age < 19
len(age[younger])

3

In [11]:
#Calculate the average marks in each subject (column-wise mean).
mathsA = maths.mean()
scienceA = science.mean()
mathsA, scienceA

(np.float64(81.6), np.float64(95.0))

In [57]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [64]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:, 2] >= 80)]

data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [38]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [49]:
#Replace all Science marks < 75 with 0.
res = data[:,2][data[:, 2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

# Valid Sudoku 
means needs the addition of every row and column should be 45, it has 9 rows and columns. the addition of 3x3 matrix should be 45.

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [21]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [ ]:
# rows sum
row = np.sum(s, axis=1)
for i in row:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("sudoko is valid")

sudoko is valid


In [ ]:
#column sum
column = np.sum(s, axis=0)
for i in column:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("sudoko is valid")

sudoko is valid


In [23]:
# 3x3 matrix sum is 45
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45
