In [87]:
import numpy as np

# vector

In [88]:
#creating array
arr = np.array([10,20,30,40,50,60])
arr1 = np.arange(1,6)
arr2 = np.linspace(1,10,3)

In [89]:
arr

array([10, 20, 30, 40, 50, 60])

In [90]:
arr1

array([1, 2, 3, 4, 5])

In [91]:
arr2

array([ 1. ,  5.5, 10. ])

In [92]:
arr.shape

(6,)

In [93]:
arr[4]

np.int64(50)

In [94]:
arr[1:]

array([20, 30, 40, 50, 60])

In [95]:
arr[:-1]

array([10, 20, 30, 40, 50])

In [96]:
arr[1:3]

array([20, 30])

In [97]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [98]:
# mathematical operations
arr.sum()

np.int64(210)

In [99]:
arr - 5

array([ 5, 15, 25, 35, 45, 55])

In [100]:
arr * 2

array([ 20,  40,  60,  80, 100, 120])

In [101]:
arr / 2

array([ 5., 10., 15., 20., 25., 30.])

In [102]:
# aggregation
arr.min()

np.int64(10)

In [103]:
arr.max()

np.int64(60)

In [104]:
arr.mean()

np.float64(35.0)

In [105]:
# boolean filtering
arr[arr > 20]

array([30, 40, 50, 60])

In [106]:
arr3 = np.array([40,30,10,20,10])
arr3

array([40, 30, 10, 20, 10])

In [107]:
#sort
arr3.sort()
arr3

array([10, 10, 20, 30, 40])

In [108]:
# broadcasting
arr4 = arr * 3
arr4

array([ 30,  60,  90, 120, 150, 180])

#Matrix

In [109]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [110]:
m.shape

(3, 3)

In [111]:
m.max()

np.int64(9)

In [112]:
#row wise
m.sum(axis=1)

array([ 6, 15, 24])

In [113]:
#column wise
m.mean(axis=0)

array([4., 5., 6.])

In [114]:
#transpose
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [115]:
m.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [116]:
# matrix multiplication
m1 = np.arange(1,7).reshape(3,2)
m2 = np.arange(6,12).reshape(3,2)
m1, m2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [117]:
#transpose
m2=m2.T
m2

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [118]:
m1 @ m2

array([[ 20,  26,  32],
       [ 46,  60,  74],
       [ 72,  94, 116]])

In [119]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [120]:
#Find even numbers.
even=v[v%2==0]
even

array([2, 4])

In [121]:
#Find odd numbers.
odd = v[v%2 != 0]
odd

array([1, 3, 5])

In [122]:
#Find maximum/minimum.
v.max()

np.int64(5)

In [123]:
v.min()

np.int64(1)

In [124]:
#Calculate mean.
v.mean()

np.float64(3.0)

In [125]:
#Reverse an array.
# v[start:stop:step]=[::-1]
v[::-1]

array([5, 4, 3, 2, 1])

In [126]:
#Remove duplicates.= np.unique(arr name)
v5=np.array([1,1,2,3,4,4,5])
np.unique(v5)


array([1, 2, 3, 4, 5])

In [127]:
# Sort an array
v.sort()

In [128]:
#Find values greater than average.
mean = v[v > v.mean()]
mean

array([4, 5])

In [129]:
v6 = np.array([-1,-2,-3,-4,-5,6,4,2])
v6

array([-1, -2, -3, -4, -5,  6,  4,  2])

In [130]:
#Replace negative values with 0. = array[condition] = new_value
v6[v6 < 0] = 0
v6

array([0, 0, 0, 0, 0, 6, 4, 2])

# Matrix

In [131]:
m2

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [132]:
e = m2[m2%2 == 0]
e

array([ 6,  8, 10])

In [133]:
odd = m2[m2%2 != 0]
odd

array([ 7,  9, 11])

In [134]:
m2.max()

np.int64(11)

In [135]:
m2.min()

np.int64(6)

In [136]:
m2.mean()

np.float64(8.5)

Code	         Meaning
arr[::-1]	    Reverse rows
arr[:, ::-1]	Reverse columns
arr[::-1, ::-1]	Reverse rows + columns

In [137]:
m2[::-1]

array([[ 7,  9, 11],
       [ 6,  8, 10]])

In [138]:

arr = np.array([
    [10, 20, 10],
    [30, 40, 20],
    [50, 30, 60]
])
arr

array([[10, 20, 10],
       [30, 40, 20],
       [50, 30, 60]])

In [139]:
# Remove duplicates.
np.unique(arr)

array([10, 20, 30, 40, 50, 60])

In [140]:
# Sort an array. column wise
np.sort(arr,axis=0)

array([[10, 20, 10],
       [30, 30, 20],
       [50, 40, 60]])

In [141]:
# row wise sort
np.sort(arr,axis=1)

array([[10, 10, 20],
       [20, 30, 40],
       [30, 50, 60]])

In [142]:
# sort whole array
np.sort(arr.flatten())


array([10, 10, 20, 20, 30, 30, 40, 50, 60])

In [143]:
#Find values greater than average.
arr[arr > arr.mean()]

array([40, 50, 60])

In [144]:
arr1 = np.array([
    [10, -20, 30],
    [-40, 50, -60],
    [70, -80, 90]
])

In [145]:
# replacing all negative values with 0
arr1[arr1 < 0] = 0
arr1

array([[10,  0, 30],
       [ 0, 50,  0],
       [70,  0, 90]])

In [146]:
arr3 = np.array([
    [10, -20, 30],
    [40, 10, -50],
    [-20, 60, 40]
])

Solve these 5 tasks:

Find all unique values.
Replace negative values with 0.
Sort each row.
Sort each column.
Reverse the complete 2D array.

In [147]:
np.unique(arr3)

array([-50, -20,  10,  30,  40,  60])

In [148]:
arr3[arr3 < 0] = 0
arr3

array([[10,  0, 30],
       [40, 10,  0],
       [ 0, 60, 40]])

In [149]:
np.sort(arr3, axis=1)


array([[ 0, 10, 30],
       [ 0, 10, 40],
       [ 0, 40, 60]])

In [ ]:
np.sort(arr3, axis=0)

array([[ 0,  0,  0],
       [10, 10, 30],
       [40, 60, 40]])

In [153]:
arr3

array([[10,  0, 30],
       [40, 10,  0],
       [ 0, 60, 40]])

In [154]:
arr3[::-1,::-1]

array([[40, 60,  0],
       [ 0, 10, 40],
       [30,  0, 10]])